name: Relocate Repository Request
description: Form to request the relocation of a remote GitHub repository to this organization
title: "[Relocate Repository]: [Source Repo Name]"
body:
  - type: input
    id: source_repository_url
    attributes:
      label: Source Repository URL
      description: Provide the URL of the repository to be relocated.
      placeholder: "https://github.com/owner/repository"

  - type: input
    id: source_repository_owner
    attributes:
      label: Owner of the Source Repository
      description: Who owns the source repository? Provide the owner/organization name and GitHub username if applicable.
      placeholder: "Owner or organization name"

  - type: input
    id: current_license
    attributes:
      label: Current License
      description: Specify the license under which the source repository is currently shared.
      placeholder: "e.g., MIT License, Apache 2.0, etc."

  - type: input
    id: destination_repository_name
    attributes:
      label: Intended Repository Name
      description: What should the name of the relocated repository be in this organization?
      placeholder: "Enter the repository name"

  - type: textarea
    id: repository_description
    attributes:
      label: Repository Description
      description: Provide a brief description of the relocated repository.
      placeholder: "Describe the repository's purpose and content"

  - type: checkboxes
    id: public_or_private
    attributes:
      label: Visibility
      description: Should the relocated repository be public or private?
      options:
        - label: "Public"
        - label: "Private"

  - type: textarea
    id: access_permissions
    attributes:
      label: Access Permissions
      description: Who should have access to this repository, and with what permissions (e.g., read, write, admin)?
      placeholder: "List users/groups and their permissions"

  - type: input
    id: repository_title
    attributes:
      label: Title (DCAT-Compatible)
      description: Provide a human-readable title for the relocated repository.
      placeholder: "Enter the title"

  - type: textarea
    id: keywords
    attributes:
      label: Keywords
      description: List keywords to describe the repository’s content (comma-separated).
      placeholder: "e.g., data, code, research"

  - type: input
    id: creator
    attributes:
      label: Creator
      description: Who is the main person or organization responsible for the source repository? Include GitHub username if applicable.
      placeholder: "Name or organization and GitHub username"

  - type: textarea
    id: contributors
    attributes:
      label: Contributors
      description: List any other contributors or collaborators for the source repository.
      placeholder: "List of contributors"

  - type: dropdown
    id: new_license
    attributes:
      label: License for the Relocated Repository
      description: Choose a license for the relocated repository.
      options:
        - "MIT License"
        - "Apache License 2.0"
        - "GPL v3"
        - "CC0"
        - "CC BY"
        - "CC BY-SA"
        - "Other (please specify below)"

  - type: input
    id: custom_license
    attributes:
      label: Custom License
      description: If you selected 'Other' above, please provide the license here.
      placeholder: "Enter your custom license"

  - type: checkboxes
    id: content_type
    attributes:
      label: Content Type
      description: What type of content does the repository contain?
      options:
        - label: "Codebase"
        - label: "Dataset"
        - label: "Documentation"
        - label: "Other (please specify below)"

  - type: textarea
    id: justification
    attributes:
      label: Justification for Relocation
      description: Provide a brief justification for why this repository should be moved to this organization.
      placeholder: "Explain why this relocation is necessary"

  - type: checkboxes
    id: dependencies
    attributes:
      label: Dependencies or Integrations
      description: Are there any dependencies or integrations that will be impacted by this move?
      options:
        - label: "Yes (please specify below)"
        - label: "No"

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Is there anything else we should know about this relocation request?
      placeholder: "Enter additional details if any"
