name: Repository Request
description: Form to request a new repository within the organization and provide metadata
title: "[Repository Request]: [Repository Name]"
body:
  - type: input
    id: repository_name
    attributes:
      label: Repository Name
      description: Provide the desired name for the repository.
      placeholder: "Enter the repository name"

  - type: input
    id: title
    attributes:
      label: Title (`dct:title`)
      description: Provide a human-readable title for the repository.
      placeholder: "Enter the title"

  - type: textarea
    id: description
    attributes:
      label: Description (`dct:description`)
      description: Provide a description of the repository, including its purpose and scope.
      placeholder: "Describe the purpose and scope of the repository"

  - type: input
    id: creator
    attributes:
      label: Creator (`dct:creator`)
      description: Who is the main person or organization responsible for creating this repository? Include their GitHub username if applicable.
      placeholder: "Name or organization and GitHub username"

  - type: textarea
    id: contributors
    attributes:
      label: Contributors (`dct:contributor`)
      description: List any other contributors or collaborators for this repository (GitHub usernames).
      placeholder: "Enter the list of contributors"

  - type: textarea
    id: keywords
    attributes:
      label: Keywords (`dcat:keyword`)
      description: List keywords (tags) that describe the repository’s content (comma-separated).
      placeholder: "e.g., data, code, research"

  - type: dropdown
    id: license
    attributes:
      label: License (`dct:license`)
      description: Specify the license for the repository.
      options:
        - "MIT License"
        - "Apache License 2.0"
        - "GPL v3"
        - "CC0 (Public Domain Dedication)"
        - "CC BY (Attribution)"
        - "CC BY-SA (Attribution-ShareAlike)"
        - "CC BY-ND (Attribution-NoDerivatives)"
        - "CC BY-NC (Attribution-NonCommercial)"
        - "CC BY-NC-SA (Attribution-NonCommercial-ShareAlike)"
        - "CC BY-NC-ND (Attribution-NonCommercial-NoDerivatives)"
        - "Other (please specify below)"

  - type: input
    id: custom_license
    attributes:
      label: Custom License
      description: If you selected 'Other' above, please specify the license.
      placeholder: "Enter your custom license"

  - type: checkboxes
    id: dataset_or_code_type
    attributes:
      label: Dataset or Code Type (`dcat:theme`)
      description: What type of content does the repository contain?
      options:
        - label: "Codebase"
        - label: "Dataset"
        - label: "Documentation"
        - label: "Other (please specify below)"

  - type: checkboxes
    id: public_or_private
    attributes:
      label: Visibility
      description: Should the repository be public or private?
      options:
        - label: "Public"
        - label: "Private"

  - type: textarea
    id: access_permissions
    attributes:
      label: Access Permissions
      description: Who should have access to this repository, and with what permissions (e.g., read, write, admin)?
      placeholder: "List users/groups and their permissions"

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Is there anything else we should know about creating this repository?
      placeholder: "Enter additional details if any"
